id: openimis.fhir.r5
canonical: https://openimis.github.io/openimis_fhir_r5_ig
name: openIMISFHIRR5
title: "openIMIS FHIR R5 Implementation Guide"
description: This IG is about the mapping and usage of FHIR R5 to integrate openIMIS with other external systems.
status: draft
license: CC0-1.0
version: 0.1.0
fhirVersion: 5.0.0
copyrightYear: 2025+
releaseLabel: ci-build
publisher:
  name: Swiss TPH
  url: https://www.swisstph.ch/en/
contact:
  - name: Dragos Dobre
    telecom:
      - system: email
        value: dragos.dobre@swisstph.ch
        use: work
  - name: Hiren Soni
    telecom:
      - system: email
        value: hiren.soni@swisstph.ch
        use: work
# template: hl7.fhir.template#current  # Commented out - using ig.ini instead

menu:
  Overview: index.html
  FHIR Design: specification.html
  Use Cases: usecases.html
  Connected Partner: connected_partner.html
  Future Plans: future.html
  Artifacts:
    Patient: artifacts.html#1
  Glossary: glossary.html
  Credits: credits.html

pages:
  index.md:
    title: openIMIS FHIR Overview
  specification.md:
    title: FHIR Design and Overview
  usecases.md:
    title: Integration Use Cases
  connected_partner.md:
    title: Becoming a Connected Partner
  future.md:
    title: Future Plans
  glossary.md:
    title: Glossary
  credits.md:
    title: Credits
