id: openimis.fhir.r5
canonical: https://openimis.github.io/openimis_fhir_r5_ig
name: openIMISFHIRR5
title: "openIMIS FHIR R5 Implementation Guide"
description: This IG is about the mapping and usage of FHIR R5 to integrate openIMIS with other external systems.
status: draft
license: CC0-1.0
version: 0.1.0
fhirVersion: 5.0.0
copyrightYear: 2025+
releaseLabel: ci-build
publisher:
  name: openIMIS Initiative
  url: https://www.openimis.org
contact:
  - name: Dragos Dobre
    telecom:
      - system: email
        value: dragos.dobre@swisstph.ch
        use: work
  - name: Hiren Soni
    telecom:
      - system: email
        value: hiren.soni@swisstph.ch
        use: work
# template: hl7.fhir.template#current  # Commented out - using ig.ini instead

menu:
  Overview: index.html
  #FHIR Design: specification.html
  Use Cases: #usecases.html
    Enrollment: usecase-enrollment.html
    Enquire: usecase-enquire.html
    Claiming: usecase-claiming.html
  #Connected Partner: connected_partner.html
  #Future Plans: future.html
  Security: security.html
  Artifacts: artifacts.html
  #Glossary: glossary.html
  Credits: credits.html

pages:
  index.md:
    title: openIMIS FHIR Overview
  #specification.md:
  #  title: FHIR Design and Overview
  usecase-enrollment.md:
    title: Enrollment Use Case
  usecase-enquire.md:
    title: Enquire Use Case
  usecase-claiming.md:
    title: Claiming Use Case
  #connected_partner.md:
  #  title: Becoming a Connected Partner
  #future.md:
  #  title: Future Plans
  #glossary.md:
  #  title: Glossary
  security.md:
    title: Security management
  credits.md:
    title: Credits
