// This is the profile for openIMIS Claim Response
// Mapping is done throught Claim openIMIS entity
Profile: OpenIMISClaimResponse
Parent: ClaimResponse
Id: openimis-claim-response
Title: "openIMIS Claim Response"
Description: "Defines a ClaimResponse for openIMIS which maps to a Claim. The ClaimResponse resource contains the adjudication result of a Claim."

* id
  * ^short = "Claim UUID"
  * ^definition = "Claim UUID generated by openIMIS."

* identifier 2..2 MS // Must contain at least the Claim Code
  * type 1..1  
  * value 1..1
* identifier.type.coding.code from OpenIMISIdentifierVS (required)
* identifier ^slicing.discriminator.type = #value
* identifier ^slicing.discriminator.path = "type.coding.code"
* identifier ^slicing.rules = #closed
* identifier contains
    Code 1..1 MS and
    UUID 1..1 
* identifier[Code].type.coding.code = OpenIMISIdentifierCS#Code // it is mapped to CHFID
  * ^short = "Claim openIMIS Code"
  * ^definition = "Claim Code managed by openIMIS."
* identifier[UUID].type.coding.code = OpenIMISIdentifierCS#UUID
  * ^short = "Claim openIMIS UUID"
  * ^definition = "Claim UUID generated by openIMIS."

* status = FHIRFinancialResourceStatusCodes#active "Active"
  * ^short = "FHIR Claim Status"
  * ^definition = "Claim status reported to FHIR Claim required Statuses."

* type.coding from ClaimVisitTypeVS (required)
  * ^short = "Visit type"
  * ^definition = "Mapped to Emergency, Referrals or Other visit type."

* use = FHIRClaimUseCodes#claim "Claim"
  * ^short = "Claim Type"
  * ^definition = "openIMIS only manages Claims."

* patient only Reference(OpenIMISPatient)

* created 1..1
  * ^definition = "Date when the claim response was created."

* insurer 1..1
* insurer only Reference(OpenIMISInsuranceOrganization)
  * ^definition = "Hardcodded as openIMIS doesn't support multiple insurance organizations."

* requestor 1..1 
* requestor only Reference(OpenIMISClaimAdministratorPractitioner)

* request 1..1

* outcome 1..1
  * ^definition = """The outcome is based on Claim status:
  * queued: entered state
  * complete: valuated or rejected state
  * partial: checked or processed state 
  """
* item 1..*
  * itemSequence 1..1
  * adjudication 0..4 // UPDATED: Min Cardinality changed from 1 to 0
    * category from ClaimStatusVS (required)
    * reason 1..1
      * coding 1..1
      * coding from ClaimRejectionReasonsVS (required)
        * ^definition = "Rejection reason."
      * text 0..1
        * ^definition = "Human justification for the decision on Item level."

    * amount 1..1
      * value 1..1
      * currency 0..1
      * ^definition = "Unit price."

    // * value 1..1 REMOVED: value is removed in R5
    //   * ^definition = "Quantity provided."
  
  * extension contains ClaimItemReferenceExtension named itemReference 1..1 
  * extension[itemReference]
    * ^short = "Item Reference"
    * ^definition = "Specifies the reference to the Medication or ActivityDefinition."

* total 1..4
  * category from ClaimStatusVS (required)
  * amount 1..1
    * value 1..1
    * currency 0..1

* processNote 0..1
  * text 1..1
    * ^definition = "Claim adjustment reason."

* communicationRequest 0..1
* communicationRequest only Reference(OpenIMISCommunicationRequest)
  * ^definition = "Provided only if the User has Claims.Feedback authority (111009)."
