// This is the profile for openIMIS Claim 
// Mapping is done throught Claim openIMIS entities
Profile: OpenIMISClaim 
Parent: Claim
Id: openimis-claim
Title: "openIMIS Claim"
Description: "Defines a Claim for openIMIS which maps to a Claim."

* id
  * ^short = "Claim UUID"
  * ^definition = "Claim UUID generated by openIMIS."

* identifier 1..2 MS // Must contain at least the Claim Code
  * type 1..1  
  * value 1..1
* identifier.type.coding.code from OpenIMISIdentifierVS (required)
* identifier ^slicing.discriminator.type = #value
* identifier ^slicing.discriminator.path = "type.coding.code"
* identifier ^slicing.rules = #closed
* identifier contains
    Code 1..1 MS and
    UUID 0..1 
* identifier[Code].type.coding.code = OpenIMISIdentifierCS#Code // it is mapped to CHFID
  * ^short = "Claim openIMIS Code"
  * ^definition = "Claim Code managed by openIMIS."
* identifier[UUID].type.coding.code = OpenIMISIdentifierCS#UUID
  * ^short = "Claim openIMIS UUID"
  * ^definition = "Claim UUID generated by openIMIS."

* status = FHIRFinancialResourceStatusCodes#active "Active"
  * ^short = "FHIR Claim Status"
  * ^definition = "Claim status reported to FHIR Claim required Statuses."

* type.coding from ClaimVisitTypeVS (required)
  * ^short = "Visit type"
  * ^definition = "Mention the visit type."

* use = FHIRClaimUseCodes#claim "Claim"
  * ^short = "Claim Type"
  * ^definition = "openIMIS only manages Claims."

* patient only Reference(OpenIMISPatient)

* billablePeriod 1..1
  * start 1..1 
    * ^short = "Start date"
    * ^definition = "Start date for the prodided services."
  * end 0..1
    * ^short = "End date"
    * ^definition = "End date for the prodided services. If missing the same as start date."

* created 1..1
  * ^short = "Claimed date"
  * ^definition = "Date when the claim was created."

* enterer 1..1 
* enterer only Reference(OpenIMISClaimAdministratorPractitioner)

* provider only Reference(OpenIMISHealthFacilityOrganization)
  * ^short = "Health Facility"
  * ^definition = "Health Facility wher the services where provided."

* priority = FHIRClaimProcessPriorityCodes#normal "Normal"

* supportingInfo 0..* 
  * sequence 1..1  
  * category 1..1
  * value[x] 1..1
  
* supportingInfo.category from ClaimSupportingInfoCategoryVS (required)
* supportingInfo ^slicing.discriminator.type = #pattern
* supportingInfo ^slicing.discriminator.path = "category"
* supportingInfo ^slicing.rules = #closed
* supportingInfo contains
    explanation 0..1 and
    guarantee 0..1 and
    attachment 0..* 
* supportingInfo[explanation]
  * category = ClaimSupportingInfoCategoryCS#explanation
  * value[x] only string 
  * ^short = "Explanation"
  * ^definition = "Explanation support info for Claim."
* supportingInfo[guarantee]
  * category = ClaimSupportingInfoCategoryCS#guarantee 
  * value[x] only string 
  * ^short = "Guarantee"
  * ^definition = "Guarantee support info for Claim."
* supportingInfo[attachment]
  * category = ClaimSupportingInfoCategoryCS#attachment 
  * value[x] only Attachment 
  * ^short = "Attachment"
  * ^definition = "Attachment support info for Claim."

* diagnosis 1..5
  * sequence 1..1
  * diagnosis[x] only CodeableConcept
  * diagnosisCodeableConcept from DiagnosisICD10Level1VS (example)
  * ^short = "Diagnosis"
  * ^definition = """One main diagnosis is mandatory. Up to four sub-diagnosis can be added if necessary. 
  The values are dependent on the actual implementation."""

* insurance 1..1
  * sequence 1..1
  * focal 1..1
  * focal = true
  * coverage only Reference(OpenIMISCoverage)
    * ^short = "Coverage"
    * ^definition = "Insuree Coverage to use. Can be obtained with CoverageEligibilityRequest."

* item 1..*
  * sequence 1..1

  * category from ClaimItemCategoryVS (required)
    * ^short = "Category"
    * ^definition = "Items category as medical item or service."

  * productOrService 1..1
    * text 1..1
      * ^short = "Item/Service Code"
      * ^definition = "Service or Item Code."
    * ^short = "Item Code"
    * ^definition = "Service or Item Code."

  * quantity 1..1
    * value 1..1
  * unitPrice 1..1
    * value 1..1
    * currency 0..1
  
  * extension contains ClaimItemReferenceExtension named itemReference 1..1 
  * extension[itemReference]
    * ^short = "Item Reference"
    * ^definition = "Specifies the reference to the Medication or ActivityDefinition."

* total 1..1
  * value 1..1
  * currency 0..1
  