// This is the profile for openIMIS Contract 
// Only for POST 
Profile: OpenIMISContract
Parent: Contract
Id: openimis-contract
Title: "openIMIS Contract"
Description: """
            Defines a Contract for openIMIS use to enrol a Family/Group. Mapped mostly to Policy and will link Group/Family and Patient/Insurees. 
            """

* id
  * ^short = "Contract UUID"
  * ^definition = "Policy UUID generated by openIMIS."

* identifier 0..* 
  * type 1..1  
  * value 1..1
* identifier.type.coding.code from OpenIMISIdentifierVS (required)
* identifier ^slicing.discriminator.type = #value
* identifier ^slicing.discriminator.path = "type.coding.code"
* identifier ^slicing.rules = #closed
* identifier contains
    UUID 0..1 
* identifier[UUID].type.coding.code = OpenIMISIdentifierCS#UUID
  * ^short = "Organization openIMIS UUID"
  * ^definition = "Health Facility UUID generated by openIMIS."

* status from ContractStatusCodesVS (required)
  * ^short = "Contract Status"
  * ^definition = """Status for a Contract. Can be either offered (idle) or executed (active). Mapped to `Policy.PolicyStatus`."""

* issued 1..1
  * ^short = "Enrolment/Renewal date"
  * ^definition = """Date when the enrolment/renewal took place. Mapped to `Policy.EnrollDate`."""

* subject 1..1
* subject only Reference(OpenIMISGroup or OpenIMISPolicyHolderOrganization)
  * ^short = "Insured Group"
  * ^definition = """Reference to the Group/Family that is enroled. Mapped to `Policy.FamilyID`."""

* authority 0..1
* authority only Reference(OpenIMISInsuranceOrganization)
  * ^short = "Insurance Instance"
  * ^definition = """Reference to the Insurance Instance."""

* author 0..1
* author only Reference(OpenIMISEnrolmentOfficerPractitioner)
  * ^short = "Enrolment Officer"
  * ^definition = """Reference to the Enrolment Officer. Mapped to `Policy.OfficerID`."""

* scope 1..1 
* scope from ContractScopeVS (required)
  * ^short = "Scope"
  * ^definition = "Indicates if the contract is for the Formal or Informal Sector."

* term 1..*
  * ^short = "Insuree Policies"
  * ^definition = """List of policies the Beneficiary Insuree is enroling to."""

  * offer 1..1 // this is mandatory in FHIR Contract
    * party 1..1
      * reference 1..1
      * reference only Reference(OpenIMISPatient)
        * ^short = "Insuree Term"
        * ^definition = """Reference to the Insuree (Head of the Family) that will be covered by the Policies."""
      * role = ContractResourcePartyRoleCS#beneficiary "Beneficiary"

  * asset 1..* 
    * ^short = "Policy"
    * ^definition = """Policy that the Beneficiary Insuree and dependent is enroling to."""

    * typeReference 1..*
    * typeReference only Reference(OpenIMISPatient)
      * ^short = "Insurees covered by a Policy"
      * ^definition = """Reference to the Insurees that will be covered by the Policy. Mapped through `tblInsureePolicy` table."""
    
    * period 1..1 // already defined by term.issued
      * start 1..1
        * ^short = "Start date"
        * ^definition = """Date when the enrolment/renewal starts. Mapped to `Policy.StartDate`."""
      * end 1..1
        * ^short = "End date"
        * ^definition = """Date when the enrolment/renewal will actual end. Mapped to `Policy.ExpiryDate`."""
    * usePeriod 1..1 // already defined by term.applies
      * start 1..1
        * ^short = "Effective date"
        * ^definition = """Date when the enrolment/renewal will actual start. Mapped to `Policy.EffectiveDate`."""
      * end 1..1
        * ^short = "End date"
        * ^definition = """Date when the enrolment/renewal will actual end. Mapped to `Policy.ExpiryDate`."""
    * valuedItem 1..*
      * entity[x] 1..1
      * entity[x] only Reference(OpenIMISInsurancePlan)
        * ^short = "InsurancePlan Reference"
        * ^definition = """Reference to the Insurance Plan the policy is related to. Mapped to `Policy.ProdID`."""
  
      * net 1..1
        * value 1..1
          * ^short = "Policy Value"
          * ^definition = """Cost of the policy. Mapped through `Policy.PolicyValue`."""
    * extension contains ContractPremiumExtension named premium 0..* MS 
    * extension[premium]
      * ^short = "Contract Premiums"
      * ^definition = "Specifies the premiums for the contract."