// This is the profile for openIMIS Claim Response
// Mapping is done through Claim openIMIS entity
Profile: OpenIMISCoverageEligibilityResponse
Parent: CoverageEligibilityResponse
Id: openimis-coverage-eligibility-response
Title: "openIMIS CoverageEligibilityResponse"
Description: "Defines a CoverageEligibilityResponse for openIMIS to get the enquire information for an Insuree."

* identifier 1..1 
  * type 1..1  
  * value 1..1
* identifier.type.coding.code from OpenIMISIdentifierVS (required)
* identifier ^slicing.discriminator.type = #value
* identifier ^slicing.discriminator.path = "type.coding.code"
* identifier ^slicing.rules = #closed
* identifier contains
    UUID 1..1 
* identifier[UUID].type.coding.code = OpenIMISIdentifierCS#UUID
  * ^short = "External System generated UUID"
  * ^definition = "UUID generated by external system to indentify the response openIMIS."

* status = FHIRFinancialResourceStatusCodes#active "Active"

* purpose 1..1
* purpose = FHIREligibilityRequestPurpose#benefits "Coverage benefits"
* patient only Reference(OpenIMISPatient)

* created 1..1

* request only Reference(OpenIMISCoverageEligibilityRequest)
* outcome = FHIRClaimProcessingCodes#complete "Processing Complete"

* insurer 1..1
* insurer only Reference(OpenIMISInsuranceOrganization)
  * ^definition = "Hardcodded as openIMIS doesn't support multiple insurance organizations."

* insurance 0..* 
  * coverage only Reference(OpenIMISCoverage)
  * benefitPeriod 1..1
    * start 1..1
      * ^short = "Benefit start day"
      * ^definition = "First day the benefit is valid (effective date)."
    * end 1..1
      * ^short = "Benefit end day"
      * ^definition = "Last day the benefit is valid (expiry date)."
  * item 1..*    // allow multiple items

  // --- Item slicing ---
  * item ^slicing.rules = #closed
  * item ^slicing.discriminator[0].type = #value
  * item ^slicing.discriminator[0].path = "category.coding.code"
  * item ^slicing.discriminator[1].type = #exists
  * item ^slicing.discriminator[1].path = "productOrService"
  * item contains
      benefit 1..1 and
      billcode 0..*

  // --- Benefit slice ---
  * item[benefit]
    * ^short = "Coverage eligibility for policy"
    * ^definition = "Coverage eligibility for policy."
    * category.coding.code = CoverageItemCategoryCS#benefit
    * name 1..1 
      * ^short = "Product/Item/Service code"
      * ^definition = "Product/Item/Service code."
    * description 1..1 
      * ^short = "Product/Item/Service name"
      * ^definition = "Product/Item/Service name."
    * benefit 0..11
    * benefit ^slicing.discriminator.type = #type
    * benefit ^slicing.discriminator.path = "allowed"
    * benefit ^slicing.rules = #closed
    * benefit contains
        total 0..6 and
        amount 0..5
    * benefit[total]
      * type from CoverageItemBenefitTypeTotalLeftVS (required)
      * allowed[x] 1..1
      * allowed[x] only unsignedInt 
    * benefit[amount]
      * type from CoverageItemBenefitTypeAmountLeftVS (required)
      * allowed[x] 1..1
      * allowed[x] only Money 
      * allowedMoney 
        * value 1..1
        * currency 0..1

  // --- Billcode slice (covers item/service codes) ---
  * item[billcode]
    * ^short = "Coverage eligibility for item or service"
    * ^definition = "Coverage eligibility for item or service with a billable code."
    * productOrService 1..1
      * text 1..1
        * ^short = "Item/Service Code"
        * ^definition = "Item or Service Code."
    * excluded 1..1 
      * ^short = "Excluded from package"
      * ^definition = "Item or service excluded from package."
    * benefit 0..2
    * benefit ^slicing.discriminator.type = #value
    * benefit ^slicing.discriminator.path = "type.coding.code"
    * benefit ^slicing.rules = #closed
    * benefit contains
        minDate 0..1 and
        itemLeft 0..1 
    * benefit[minDate]
      * type = CoverageItemBenefitTypeCS#min_date_item "Minimum date"
      * allowed[x] only string 
    * benefit[itemLeft]
      * type = CoverageItemBenefitTypeCS#item_left "Items left"
      * allowed[x] only unsignedInt 
