// This is the profile for openIMIS Claim Response
// Mapping is done throught Claim openIMIS entity
Profile: OpenIMISCoverageEligibilityRequest
Parent: CoverageEligibilityRequest
Id: openimis-coverage-eligibility-request
Title: "openIMIS CoverageEligibilityRequest"
Description: "Defines a CoverageEligibilityRequest for openIMIS to enquire an Insuree."

* identifier 1..1 
  * type 1..1  
  * value 1..1
* identifier.type.coding.code from OpenIMISIdentifierVS (required)
* identifier ^slicing.discriminator.type = #value
* identifier ^slicing.discriminator.path = "type.coding.code"
* identifier ^slicing.rules = #closed
* identifier contains
    UUID 1..1 
* identifier[UUID].type.coding.code = OpenIMISIdentifierCS#UUID
  * ^short = "External System generated UUID"
  * ^definition = "UUID generated by external system to indentify the response openIMIS."

* status = FHIRFinancialResourceStatusCodes#active "Active"


* purpose 1..1
* purpose = FHIREligibilityRequestPurpose#benefits "Coverage benefits"
* patient only Reference(OpenIMISPatient)

* created 1..1

* insurer 1..1
* insurer only Reference(OpenIMISInsuranceOrganization)
  * ^definition = "Hardcodded as openIMIS doesn't support multiple insurance organizations."

* item 0..2
  * category from CoverageItemCategoryVS (required)
    * ^short = "Category"
    * ^definition = "Items category as medical item or service."
  * productOrService 1..1
    * text 1..1
      * ^short = "Item/Service Code"
      * ^definition = "Service or Item Code."
    * ^short = "Item Code"
    * ^definition = "Service or Item Code."

* item ^slicing.discriminator.type = #value
* item ^slicing.discriminator.path = "category.coding.code"
* item ^slicing.rules = #closed
* item contains
    item 0..1 and
    service 0..1
* item[item].category.coding.code = CoverageItemCategoryCS#item
* item[item]
  * ^short = "Coverage eligibility for item"
  * ^definition = "Coverage eligibility for item."
* item[service].category.coding.code = CoverageItemCategoryCS#service
* item[service]
  * ^short = "Coverage eligibility for service"
  * ^definition = "Coverage eligibility for service."

