// This is the profile for openIMIS Organization 
// Mapping is done throught Policy Holder openIMIS entity
Profile: OpenIMISPolicyHolderOrganization
Parent: Organization
Id: openimis-policy-holder-organization
Title: "openIMIS Policy Holder Organization"
Description: "Defines an Organization for openIMIS which maps to a Policy Holder under Formal Sector scheme."

* id
  * ^short = "Organization UUID"
  * ^definition = "Organization UUID generated by openIMIS."

* identifier 1..* MS // Must contain at least the HF Code
  * type 1..1  
  * value 1..1
* identifier.type.coding.code from OpenIMISIdentifierVS (required)
* identifier ^slicing.discriminator.type = #value
* identifier ^slicing.discriminator.path = "type.coding.code"
* identifier ^slicing.rules = #closed
* identifier contains
    Code 1..1 MS and
    UUID 0..1 
* identifier[Code].type.coding.code = OpenIMISIdentifierCS#Code // it is mapped to Code
  * ^short = "Organization openIMIS Code"
  * ^definition = "PolicyHolder Code managed by openIMIS."
* identifier[UUID].type.coding.code = OpenIMISIdentifierCS#UUID
  * ^short = "Organization openIMIS UUID"
  * ^definition = "PolicyHolder UUID generated by openIMIS."
* type 1..1
* type.coding.code = OrganizationTypeCS#bus
* name 1..1 
* contact 0..1
  * purpose = ContactEntityTypeCS#PAYOR
  * name 1..1
    * text 1..1
  * ^short = "PolicyHolder contact"
  * ^definition = "PolicyHolder contact details. "
  * telecom 0..3 MS
    * value 1..1 
  * telecom ^slicing.discriminator.type = #value
  * telecom ^slicing.discriminator.path = "system"
  * telecom ^slicing.rules = #open
  * telecom contains
      email 0..1 and
      phone 0..1 and 
      fax 0..1 
  * telecom[email].system = #email 
    * ^short = "PolicyHolder email"
    * ^definition = "PolicyHolder email contact."
  * telecom[phone].system = #phone
    * ^short = "PolicyHolder phone"
    * ^definition = "PolicyHolder phone contact."
  * telecom[fax].system = #fax
    * ^short = "PolicyHolder fax"
    * ^definition = "PolicyHolder fax contact."

    * type = FHIRAddressType#physical

    // Location.LocationName from HF's Region (HF.LocationId.ParentLocationId)
    * state 1..1 MS // mapped to Region 
      * ^short = "State/Region"
      * ^definition = "PolicyHolder's State/Region name as it is configured in openIMIS."
    // Location.LocationName from HF's District (HF.LocationId)
    * district 1..1 MS // mapped to District 
      * ^short = "District"
      * ^definition = "PolicyHolder's District name as it is configured in openIMIS."
    * extension contains AddressMunicipalityExtension named municipality 1..1 MS // mapped to Ward (see previous two comments) !!!
      * ^short = "Municipality/Ward"
      * ^definition = "Insuree's Municipality/Ward name as it is configured in openIMIS."
    * city 1..1 MS // Location.LocationName from Family's City (Family.LocationId) or Insuree's City (Insuree.CurrentVillage)
      * ^short = "City/Village"
      * ^definition = "Insuree's City/Village name as it is configured in openIMIS."

    * line 0..1 // HFAddress
    * extension contains AddressLocationReferenceExtension named location 1..1 MS 

* extension contains OrganizationPHLegalFormExtension named legalForm 0..1 
* extension[legalForm]
  * ^short = "Legal Form"
  * ^definition = "Specifies the Organization's Legal Form."

* extension contains OrganizationPHActivityExtension named activity 0..1 
* extension[activity]
  * ^short = "PolicyHolder Activity"
  * ^definition = "Specifies the PolicyHolder's Activity."
