// This is the profile for openIMIS Practitioner 
// Mapping is done throught Enrolment Officer openIMIS entities
Profile: OpenIMISEnrolmentOfficerPractitionerRole
Parent: PractitionerRole
Id: openimis-enrolment-officer-practitioner-role
Title: "openIMIS Enrolment Officer Practitioner Role"
Description: "Defines a Enrolment Officer Practitioner Role for openIMIS."

* id
  * ^short = "Practitioner UUID"
  * ^definition = "Enrolment Officer UUID generated by openIMIS."

* identifier 1..* MS // Must contain at least the Claim Administrator/Enrolment Officer Code
  * type 1..1  
  * value 1..1
* identifier.type.coding.code from OpenIMISIdentifierVS (required)
* identifier ^slicing.discriminator.type = #value
* identifier ^slicing.discriminator.path = "type.coding.code"
* identifier ^slicing.rules = #closed
* identifier contains
    Code 1..1 MS and
    UUID 0..1 
* identifier[Code].type.coding.code = OpenIMISIdentifierCS#Code // it is mapped to CHFID
  * ^short = "openIMIS Code"
  * ^definition = "Enrolment Officer Code managed by openIMIS."
* identifier[UUID].type.coding.code = OpenIMISIdentifierCS#UUID
  * ^short = "openIMIS UUID"
  * ^definition = "Enrolment Officer UUID generated by openIMIS."

* period 0..1

  * end 1..1 
    * ^short = "Works To"
    * ^definition = "Date until the Enrolment Officer works."
  

* practitioner 1..1
* practitioner only Reference(OpenIMISEnrolmentOfficerPractitioner)

* code = PractitionerQualificationTypeCS#EO "Enrolment Officer"

* location 0..*
* location only Reference(OpenIMISLocation)

* contact 0..*
  * purpose 1..1
  * purpose = ContactEntityTypeCS#PAYOR
  * name 1..1
  * telecom 0..2 
    * value 1..1 
  * telecom ^slicing.discriminator.type = #value
  * telecom ^slicing.discriminator.path = "system"
  * telecom ^slicing.rules = #closed
  * telecom contains
      email 0..1 and
      phone 0..1
  * telecom[email]
    * system = FHIRContactPointSystemCS#email 
    * ^short = "Enrolment Officer email"
    * ^definition = "Enrolment Officer email contact."
  * telecom[phone]
    * system = FHIRContactPointSystemCS#phone
    * ^short = "Enrolment Officer phone"
    * ^definition = "Enrolment Officer phone contact."

* extension contains PractitionerRoleSubstitutionReferenceExtension named substitution 0..1 
* extension[substitution]
  * ^short = "Substitution"
  * ^definition = "The reference to the Enrolment Officer that will substitute the current one after the period end."
